# Generated by Django 4.2.1 on 2023-07-18 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybo', '0004_answer_modify_date_question_modify_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='star',
            field=models.ManyToManyField(blank=True, related_name='stars', to=settings.AUTH_USER_MODEL),
        ),
    ]
